# Blueprint for deploying the Guestbook application on Render.com

services:
  # Backend Web Service
  - type: web
    name: guestbookapi
    env: node
    plan: free
    rootDir: server
    buildCommand: "npm install"
    startCommand: "npm run start"
    healthCheckPath: /health
    envVars:
      - key: DATABASE_URL
        sync: false
      - key: RECAPTCHA_SECRET_KEY
        sync: false

  # Frontend Static Site
  - type: web
    name: guestbook
    runtime: static
    rootDir: client
    build:
      buildCommand: "npm install && npm run build"
      publishDir: "./dist"
    routes:
      - type: rewrite
        source: /api/*
        destination: https://guestbookapi.onrender.com/api/*
    envVars:
      - key: VITE_RECAPTCHA_SITE_KEY
        sync: false